#!/usr/bin/env bash
# This scripts prints "Best School" 10 times
# but "Hi" on the 9th interation

count=1

while [ $count -le 10]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"

	fi
	count=$((count+1))

done
